/**
 * 50 inspiring New York City trip templates — neighborhood-first, exciting,
 * and aligned with personalize day categories.
 *
 * Category titles must match experienceCategoryLabel in trip-templates.ts
 * (kept local to avoid a circular import).
 */
import type {
  ComfortLevel,
  ExperienceCategory,
  ExperienceOption,
  TripBlock,
  TripTemplate,
} from "@/lib/trip-templates";

const experienceCategoryLabel: Record<ExperienceCategory, string> = {
  SIGHTS: "Famous sights",
  FOOD: "Food tour",
  CULTURE: "Museums / culture",
  NATURE: "Nature / parks day",
  LIVE_ENTERTAINMENT: "Live entertainment / show",
  SHOPPING: "Shopping day",
  FAMILY: "Children’s activities",
  RELAX: "Relaxation / spa",
  NIGHTLIFE: "Nightlife",
  RELIGIOUS: "Religious / spiritual sites",
  FREE_TIME: "Free time / slow day",
  WATER_ACTIVITY: "Waterpark / theme park",
  PRIVATE_GROUP_EVENT: "Private group dinner",
  THEME_PARK: "Theme park",
};

type DaySeed = {
  label: string;
  defaultCat: ExperienceCategory;
  summary: string;
  minutes?: number;
  options: Array<{
    cat: ExperienceCategory;
    place: string;
    viator?: string;
    special?: boolean;
  }>;
};

type NycSeed = {
  id: string;
  slug: string;
  title: string;
  days: number;
  route: string;
  bestFor: string[];
  comfort: ComfortLevel;
  blurb: string;
  saved?: number;
  groups?: number;
  daySeeds: DaySeed[];
};

function opt(
  id: string,
  cat: ExperienceCategory,
  place: string,
  viator?: string,
  special?: boolean,
): ExperienceOption {
  return {
    id,
    category: cat,
    title: experienceCategoryLabel[cat],
    summary: place,
    viatorQuery: viator,
    specialProviderRequired: special,
  };
}

function buildBlocks(prefix: string, daySeeds: DaySeed[]): TripBlock[] {
  return daySeeds.map((d, i) => {
    const alternatives = d.options.map((o, j) =>
      opt(`${prefix}-d${i + 1}-o${j + 1}`, o.cat, o.place, o.viator, o.special),
    );
    const alts = alternatives.map((a) => ({
      ...a,
      title: experienceCategoryLabel[a.category],
    }));
    return {
      id: `${prefix}-d${i + 1}`,
      kind: "flexible" as const,
      dayLabel: d.label,
      title: experienceCategoryLabel[d.defaultCat],
      summary: d.summary,
      category: d.defaultCat,
      fromHotelMinutes: d.minutes,
      viatorCitySlug: "new-york",
      viatorQuery: d.options.find((o) => o.cat === d.defaultCat)?.viator,
      alternatives: alts,
    };
  });
}

function nyc(seed: NycSeed, index: number): TripTemplate {
  return {
    id: seed.id,
    slug: seed.slug,
    scale: "city",
    title: seed.title,
    countries: ["United States"],
    countryCodes: ["US"],
    cityCodes: ["NYC"],
    region: "Northeast",
    days: seed.days,
    route: seed.route,
    bestFor: seed.bestFor,
    comfort: seed.comfort,
    blurb: seed.blurb,
    savedCount: seed.saved ?? 400 + ((index * 37) % 900),
    groupsUsed: seed.groups ?? 40 + ((index * 11) % 200),
    recommendPercent: 86 + (index % 10),
    keptOrderPercent: 64 + (index % 16),
    travelledRating: 4.6 + ((index % 4) * 0.1),
    travelledReviews: 24 + ((index * 13) % 180),
    blocks: buildBlocks(seed.id, seed.daySeeds),
  };
}

const commonFlex = (
  sights: string,
  food: string,
  culture: string,
  extra?: Array<DaySeed["options"][number]>,
): DaySeed["options"] => [
  { cat: "SIGHTS", place: sights, viator: "New York sightseeing" },
  { cat: "FOOD", place: food, viator: "New York food tour" },
  { cat: "CULTURE", place: culture, viator: "museum" },
  { cat: "NATURE", place: "Park time nearby — green reset.", viator: "Central Park" },
  { cat: "FREE_TIME", place: "Leave the day soft — no forced agenda." },
  ...(extra || []),
];

const seeds: NycSeed[] = [
  {
    id: "nyc-inspire-01",
    slug: "nyc-neon-noodles-night-trains",
    title: "Neon, Noodles & Night Trains",
    days: 3,
    route: "LES → Brooklyn → Queens",
    bestFor: ["Food lovers", "Night owls", "Return visitors"],
    comfort: "active",
    blurb:
      "Skip the checklist — chase river glow, indie museums, and late noodles across three boroughs.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Lower East Side — markets, dumplings, and tenement stories.",
        minutes: 25,
        options: commonFlex(
          "East River waterfront walk at dusk.",
          "Essex Market + Chinatown dumpling crawl.",
          "Tenement Museum or New Museum afternoon.",
          [{ cat: "NIGHTLIFE", place: "LES bars and late slices." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "CULTURE",
        summary: "Williamsburg / Greenpoint creative pocket.",
        minutes: 35,
        options: commonFlex(
          "Waterfront skyline from Brooklyn.",
          "Williamsburg pizza and coffee crawl.",
          "Street art and indie gallery hop.",
          [{ cat: "SHOPPING", place: "Independent shops along Bedford." }],
        ),
      },
      {
        label: "Day 3",
        defaultCat: "FOOD",
        summary: "Queens flavors — Jackson Heights or Long Island City views.",
        minutes: 40,
        options: commonFlex(
          "LIC waterfront + Manhattan skyline.",
          "Jackson Heights global street-food day.",
          "Small museum or sculpture park stop.",
          [{ cat: "WATER_ACTIVITY", place: "East River ferry hop.", viator: "NYC ferry" }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-02",
    slug: "nyc-first-weekend-done-right",
    title: "First Weekend — Done Right",
    days: 3,
    route: "Midtown → Downtown → Bridge",
    bestFor: ["First timers", "Weekenders"],
    comfort: "balanced",
    blurb:
      "The smart first weekend: icons without burnout, one great show, one skyline moment.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Midtown icons near the hotel — soft landing.",
        minutes: 15,
        options: commonFlex(
          "Midtown landmarks walk.",
          "Quick Midtown bites between sights.",
          "MoMA if energy allows.",
          [{ cat: "LIVE_ENTERTAINMENT", place: "Broadway evening.", viator: "Broadway" }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "Harbor classics — Liberty energy without chaos.",
        minutes: 35,
        options: commonFlex(
          "Statue of Liberty / harbor day.",
          "FiDi food after the ferry.",
          "9/11 Memorial Museum.",
          [{ cat: "WATER_ACTIVITY", place: "Harbor cruise.", viator: "Statue of Liberty" }],
        ),
      },
      {
        label: "Day 3",
        defaultCat: "NATURE",
        summary: "Brooklyn Bridge morning + park buffer.",
        minutes: 30,
        options: commonFlex(
          "Brooklyn Bridge + DUMBO views.",
          "DUMBO pizza with skyline.",
          "One last museum morning.",
          [{ cat: "RELAX", place: "Easy cafe morning before checkout." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-03",
    slug: "nyc-broadway-hells-kitchen",
    title: "Broadway & Hell’s Kitchen",
    days: 3,
    route: "Theater District loop",
    bestFor: ["Show lovers", "Couples", "Groups"],
    comfort: "balanced",
    blurb:
      "Curtain calls, restaurant row, and walkable evenings — built around a real show night.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "LIVE_ENTERTAINMENT",
        summary: "Settle in and catch a show.",
        minutes: 10,
        options: [
          { cat: "LIVE_ENTERTAINMENT", place: "Broadway night — book early.", viator: "Broadway" },
          { cat: "FOOD", place: "Hell’s Kitchen pre-theater dinner.", viator: "Hell's Kitchen food" },
          { cat: "SIGHTS", place: "Times Square once — then leave.", viator: "Times Square" },
          { cat: "NIGHTLIFE", place: "Post-show drinks nearby." },
          { cat: "FREE_TIME", place: "Light night after travel." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "Day sights, second show optional.",
        minutes: 20,
        options: commonFlex(
          "SUMMIT or Edge observation.",
          "Theater District lunch crawl.",
          "Museum of Broadway or MoMA.",
          [{ cat: "LIVE_ENTERTAINMENT", place: "Matinee or second show.", viator: "Broadway" }],
        ),
      },
      {
        label: "Day 3",
        defaultCat: "FOOD",
        summary: "Brunch and soft exit.",
        minutes: 15,
        options: commonFlex(
          "One last Midtown photo stop.",
          "Hell’s Kitchen brunch.",
          "Quiet gallery hour.",
          [{ cat: "SHOPPING", place: "Gifts near the hotel." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-04",
    slug: "nyc-brooklyn-bridge-sunrise-romance",
    title: "Brooklyn Bridge Sunrise Romance",
    days: 2,
    route: "DUMBO → West Village",
    bestFor: ["Couples", "Anniversaries", "Photographers"],
    comfort: "relaxed",
    blurb:
      "Early bridge light, skyline pizza, and a West Village evening that feels like a movie.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "NATURE",
        summary: "Sunrise bridge walk before the crowds.",
        minutes: 30,
        options: [
          { cat: "NATURE", place: "Brooklyn Bridge at sunrise + Bridge Park.", viator: "Brooklyn Bridge" },
          { cat: "FOOD", place: "Juliana’s / DUMBO pizza with a view.", viator: "DUMBO food" },
          { cat: "SIGHTS", place: "Skyline photos from the waterfront." },
          { cat: "RELAX", place: "Slow coffee in DUMBO." },
          { cat: "PRIVATE_GROUP_EVENT", place: "Private dinner reservation.", special: true },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "West Village streets and date-night energy.",
        minutes: 25,
        options: commonFlex(
          "Village brownstone wander.",
          "West Village dinner (book ahead).",
          "Small museum or comedy club.",
          [{ cat: "NIGHTLIFE", place: "Intimate Village bar hop." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-05",
    slug: "nyc-lower-east-side-food-culture",
    title: "Lower East Side — Food & Culture",
    days: 2,
    route: "Orchard → Essex → Chinatown",
    bestFor: ["Foodies", "History lovers"],
    comfort: "balanced",
    blurb:
      "Immigrant food history, Essex Market bites, and culture within a few electric blocks.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Tenement stories + market tasting.",
        minutes: 25,
        options: [
          { cat: "CULTURE", place: "Tenement Museum guided tour.", viator: "Tenement Museum" },
          { cat: "FOOD", place: "Essex Market tasting loop.", viator: "Lower East Side food" },
          { cat: "SIGHTS", place: "Orchard Street wander." },
          { cat: "SHOPPING", place: "Boutique + candy-shop detours." },
          { cat: "NIGHTLIFE", place: "LES evening energy." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "Chinatown dumpling morning into SoHo.",
        minutes: 30,
        options: commonFlex(
          "Walk into SoHo cast-iron streets.",
          "Chinatown dumpling and bun crawl.",
          "New Museum or ICP photography.",
          [{ cat: "RELAX", place: "Slow tea and soft afternoon." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-06",
    slug: "nyc-harlem-soul-jazz",
    title: "Harlem Soul & Jazz",
    days: 2,
    route: "Harlem core",
    bestFor: ["Music lovers", "Culture", "Food"],
    comfort: "balanced",
    blurb:
      "Soul food institutions, gospel or jazz evenings, and uptown swagger.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Harlem classics on the plate.",
        minutes: 40,
        options: [
          { cat: "FOOD", place: "Soul food pilgrimage (Sylvia’s / Amy Ruth’s energy).", viator: "Harlem food tour" },
          { cat: "CULTURE", place: "Apollo / Harlem heritage walk.", viator: "Harlem tour" },
          { cat: "LIVE_ENTERTAINMENT", place: "Jazz night.", viator: "Harlem jazz" },
          { cat: "SIGHTS", place: "Brownstone streets and Marcus Garvey Park." },
          { cat: "RELIGIOUS", place: "Historic Harlem churches." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "CULTURE",
        summary: "Museums uptown + softer finish.",
        minutes: 35,
        options: commonFlex(
          "Uptown viewpoints.",
          "More Harlem bites.",
          "Studio Museum / nearby culture.",
          [{ cat: "LIVE_ENTERTAINMENT", place: "Matinee music if available." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-07",
    slug: "nyc-queens-global-eats",
    title: "Queens Global Eats",
    days: 2,
    route: "Jackson Heights → Flushing → LIC",
    bestFor: ["Serious foodies", "Adventurous eaters"],
    comfort: "active",
    blurb:
      "The world’s borough on a plate — South Asian, Latin, Korean, and Chinese classics.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Jackson Heights sensory day.",
        minutes: 45,
        options: [
          { cat: "FOOD", place: "Jackson Heights street-food marathon.", viator: "Queens food tour" },
          { cat: "CULTURE", place: "Neighborhood bookshops and cultural stops." },
          { cat: "SHOPPING", place: "Sari shops and jewelry windows." },
          { cat: "FREE_TIME", place: "Graze slowly — no rush." },
          { cat: "SIGHTS", place: "Neighborhood street photography." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "Flushing dumplings or Murray Hill Korean.",
        minutes: 50,
        options: [
          { cat: "FOOD", place: "Flushing food court + dumplings.", viator: "Flushing food" },
          { cat: "FOOD", place: "Murray Hill Korean BBQ night.", viator: "Korean BBQ Queens" },
          { cat: "SIGHTS", place: "LIC skyline golden hour." },
          { cat: "WATER_ACTIVITY", place: "Ferry back with views.", viator: "NYC ferry" },
          { cat: "RELAX", place: "Soft landing after the feast." },
        ],
      },
    ],
  },
  {
    id: "nyc-inspire-08",
    slug: "nyc-museum-mile-power",
    title: "Museum Mile Power Weekend",
    days: 3,
    route: "UES museum spine",
    bestFor: ["Art lovers", "Indoor-friendly", "Couples"],
    comfort: "relaxed",
    blurb:
      "Met, Guggenheim, and park buffers — culture without sprinting Midtown.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "The Met deep dive.",
        minutes: 25,
        options: [
          { cat: "CULTURE", place: "Metropolitan Museum highlights.", viator: "Metropolitan Museum" },
          { cat: "NATURE", place: "Central Park after the Met.", viator: "Central Park" },
          { cat: "FOOD", place: "UES cafe and bakery stops." },
          { cat: "SHOPPING", place: "Museum shop treasures." },
          { cat: "RELAX", place: "Only one museum — then rest." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "CULTURE",
        summary: "Guggenheim or Neue Galerie.",
        minutes: 25,
        options: commonFlex(
          "Museum Mile architecture walk.",
          "UES lunch.",
          "Guggenheim spiral afternoon.",
          [{ cat: "CULTURE", place: "Second museum if stamina holds.", viator: "Guggenheim" }],
        ),
      },
      {
        label: "Day 3",
        defaultCat: "NATURE",
        summary: "Park morning + soft checkout.",
        minutes: 20,
        options: commonFlex(
          "Conservatory Garden stroll.",
          "Brunch nearby.",
          "One last gallery.",
          [{ cat: "FREE_TIME", place: "Sleep in and wander." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-09",
    slug: "nyc-central-park-deep-dive",
    title: "Central Park Deep Dive",
    days: 2,
    route: "Park loops + UWS",
    bestFor: ["Nature lovers", "Families", "Joggers"],
    comfort: "active",
    blurb:
      "The park as the main character — boats, paths, and a museum on the edge.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "NATURE",
        summary: "Long park day from south to north.",
        minutes: 20,
        options: [
          { cat: "NATURE", place: "Full Central Park loop / bike.", viator: "Central Park bike" },
          { cat: "FAMILY", place: "Zoo or playground focus.", viator: "Central Park Zoo" },
          { cat: "FOOD", place: "Picnic or park-adjacent eats." },
          { cat: "CULTURE", place: "Met or Natural History on the rim.", viator: "museum" },
          { cat: "RELAX", place: "Lawn time only." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "CULTURE",
        summary: "UWS museum morning.",
        minutes: 20,
        options: commonFlex(
          "UWS brownstone wander.",
          "Bagel’s / neighborhood bites.",
          "American Museum of Natural History.",
          [{ cat: "FAMILY", place: "Kid-paced museum morning." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-10",
    slug: "nyc-harbor-heroes",
    title: "Harbor Heroes",
    days: 2,
    route: "Battery → Liberty → ferry",
    bestFor: ["First timers", "Families", "Photographers"],
    comfort: "balanced",
    blurb:
      "Statue, skyline, and salt air — the harbor day people remember forever.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Liberty / Ellis focus.",
        minutes: 40,
        options: [
          { cat: "SIGHTS", place: "Statue of Liberty & Ellis Island.", viator: "Statue of Liberty" },
          { cat: "WATER_ACTIVITY", place: "Harbor cruise alternative.", viator: "NYC harbor cruise" },
          { cat: "CULTURE", place: "9/11 Memorial Museum.", viator: "9/11 Museum" },
          { cat: "FOOD", place: "FiDi / Seaport eats." },
          { cat: "FAMILY", place: "Shorter harbor loop with kids." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "WATER_ACTIVITY",
        summary: "Staten Island Ferry + soft downtown.",
        minutes: 35,
        options: [
          { cat: "WATER_ACTIVITY", place: "Staten Island Ferry round trip (free views)." },
          { cat: "SIGHTS", place: "Wall Street / Charging Bull stroll." },
          { cat: "FOOD", place: "Seaport lunch." },
          { cat: "RELAX", place: "Battery Park lawn time." },
          { cat: "FREE_TIME", place: "Open downtown afternoon." },
        ],
      },
    ],
  },
];

// Continue seeds 11-50 in a second array for readability
const seedsContinued: NycSeed[] = [
  {
    id: "nyc-inspire-11",
    slug: "nyc-high-line-chelsea",
    title: "High Line to Chelsea Market",
    days: 2,
    route: "Meatpacking → Chelsea",
    bestFor: ["Walkers", "Food", "Design lovers"],
    comfort: "balanced",
    blurb: "Elevated park views, market bites, and gallery blocks.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "NATURE",
        summary: "High Line end-to-end.",
        minutes: 25,
        options: commonFlex(
          "Whitney or Hudson Yards viewpoint.",
          "Chelsea Market tasting.",
          "Chelsea gallery afternoon.",
          [{ cat: "SHOPPING", place: "Design shops along the way." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "CULTURE",
        summary: "More galleries or Vessel once.",
        minutes: 25,
        options: commonFlex(
          "Vessel / Hudson Yards look.",
          "Chelsea lunch.",
          "More gallery hopping.",
          [{ cat: "RELAX", place: "Spa / soft afternoon nearby." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-12",
    slug: "nyc-west-village-date-night",
    title: "West Village Date Night",
    days: 2,
    route: "West Village streets",
    bestFor: ["Couples", "Foodies"],
    comfort: "relaxed",
    blurb: "Crooked streets, candlelit tables, and zero rush.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Reservation-worthy dinner night.",
        minutes: 25,
        options: [
          { cat: "FOOD", place: "West Village dinner (book ahead).", viator: "West Village food" },
          { cat: "SIGHTS", place: "Brownstone golden-hour walk." },
          { cat: "NIGHTLIFE", place: "Cocktail bar crawl." },
          { cat: "LIVE_ENTERTAINMENT", place: "Comedy or small venue." },
          { cat: "PRIVATE_GROUP_EVENT", place: "Private tasting table.", special: true },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "RELAX",
        summary: "Brunch and bookstore wandering.",
        minutes: 20,
        options: commonFlex(
          "Hudson River Park stroll.",
          "Village brunch.",
          "Independent bookstores.",
          [{ cat: "SHOPPING", place: "Boutique window shopping." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-13",
    slug: "nyc-east-village-slice-crawl",
    title: "East Village Slice Crawl",
    days: 2,
    route: "East Village → Bowery",
    bestFor: ["Food", "Night energy", "Budget-friendly"],
    comfort: "active",
    blurb: "Best-dollar pizza, weird wonderful streets, late nights.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Slice crawl + evening bars.",
        minutes: 25,
        options: [
          { cat: "FOOD", place: "East Village pizza crawl.", viator: "East Village food" },
          { cat: "NIGHTLIFE", place: "1st Avenue bar hop." },
          { cat: "LIVE_ENTERTAINMENT", place: "Live music dive." },
          { cat: "CULTURE", place: "Small galleries / street culture." },
          { cat: "FREE_TIME", place: "Wander without a list." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "CULTURE",
        summary: "Bowery culture + soft landing.",
        minutes: 25,
        options: commonFlex(
          "Bowery wander.",
          "More EV eats.",
          "New Museum.",
          [{ cat: "RELAX", place: "Slow coffee morning." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-14",
    slug: "nyc-dumbo-skyline-pizza",
    title: "DUMBO Skyline & Pizza",
    days: 2,
    route: "DUMBO waterfront",
    bestFor: ["Photographers", "Couples", "Families"],
    comfort: "relaxed",
    blurb: "Manhattan framed by the bridge — pizza optional but recommended.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Iconic photo spots + park.",
        minutes: 30,
        options: commonFlex(
          "Washington St skyline shot + Bridge Park.",
          "Juliana’s / Grimaldi’s energy pizza.",
          "Time Out Market browse.",
          [{ cat: "FAMILY", place: "Playgrounds along the park." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Brooklyn Bridge walk back.",
        minutes: 30,
        options: commonFlex(
          "Bridge walk into Manhattan.",
          "Seaport lunch.",
          "One downtown museum.",
          [{ cat: "WATER_ACTIVITY", place: "Short ferry hop." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-15",
    slug: "nyc-williamsburg-creative",
    title: "Williamsburg Creative Day",
    days: 2,
    route: "Bedford Ave belt",
    bestFor: ["Creatives", "Shoppers", "Food"],
    comfort: "balanced",
    blurb: "Murals, makers, waterfront golden hour.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Street art and indie shops.",
        minutes: 35,
        options: commonFlex(
          "Waterfront Domino Park views.",
          "Smorgasburg / food hall vibes (seasonal).",
          "Gallery and mural walk.",
          [{ cat: "SHOPPING", place: "Vintage and design shops." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "Coffee, pizza, soft exit.",
        minutes: 35,
        options: commonFlex(
          "More waterfront photos.",
          "Neighborhood brunch.",
          "Small museum if open.",
          [{ cat: "NIGHTLIFE", place: "Williamsburg evening out." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-16",
    slug: "nyc-rainy-day-indoor-icons",
    title: "Rainy Day Indoor Icons",
    days: 2,
    route: "Grand Central → museums → markets",
    bestFor: ["Bad weather", "Culture", "Food halls"],
    comfort: "relaxed",
    blurb: "When the sky opens, New York still delivers indoors.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Museums and covered markets.",
        minutes: 20,
        options: [
          { cat: "CULTURE", place: "MoMA or Met — pick one deep dive.", viator: "MoMA" },
          { cat: "FOOD", place: "Chelsea Market or Grand Central bites." },
          { cat: "SIGHTS", place: "Grand Central interior wander." },
          { cat: "SHOPPING", place: "Indoor mall / Hudson Yards shops." },
          { cat: "RELAX", place: "Spa afternoon.", viator: "spa New York" },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "Observation decks and atriums.",
        minutes: 20,
        options: [
          { cat: "SIGHTS", place: "SUMMIT or Edge (weather-proof views).", viator: "SUMMIT" },
          { cat: "CULTURE", place: "Second museum day.", viator: "museum" },
          { cat: "FOOD", place: "Food hall hopping." },
          { cat: "LIVE_ENTERTAINMENT", place: "Matinee show.", viator: "Broadway" },
          { cat: "FREE_TIME", place: "Hotel day + one outing." },
        ],
      },
    ],
  },
  {
    id: "nyc-inspire-17",
    slug: "nyc-family-midtown-soft",
    title: "Family Midtown Soft Landing",
    days: 3,
    route: "Midtown family loop",
    bestFor: ["Families", "First timers with kids"],
    comfort: "relaxed",
    blurb: "Short hops, kid pacing, one magical show, lots of snacks.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FAMILY",
        summary: "Easy icons near the hotel.",
        minutes: 15,
        options: [
          { cat: "FAMILY", place: "Kid-paced Midtown sights.", viator: "family New York" },
          { cat: "SIGHTS", place: "Times Square once, early." },
          { cat: "FOOD", place: "Kid-friendly Midtown dinner." },
          { cat: "LIVE_ENTERTAINMENT", place: "Lion King / Aladdin-style show.", viator: "Broadway family" },
          { cat: "RELAX", place: "Early night after travel." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Central Park play day.",
        minutes: 20,
        options: [
          { cat: "NATURE", place: "Park playgrounds + boat weather permitting.", viator: "Central Park" },
          { cat: "FAMILY", place: "Central Park Zoo.", viator: "Central Park Zoo" },
          { cat: "CULTURE", place: "Natural History Museum.", viator: "Natural History Museum" },
          { cat: "FOOD", place: "Simple park-adjacent meals." },
          { cat: "FREE_TIME", place: "Nap-friendly afternoon." },
        ],
      },
      {
        label: "Day 3",
        defaultCat: "SIGHTS",
        summary: "One big view, then buffer.",
        minutes: 20,
        options: commonFlex(
          "Observation deck with kids.",
          "Easy lunch.",
          "Interactive museum hour.",
          [{ cat: "SHOPPING", place: "Souvenir hour only." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-18",
    slug: "nyc-architecture-obsession",
    title: "Architecture Obsession",
    days: 3,
    route: "Midtown → FiDi → Brooklyn views",
    bestFor: ["Design nerds", "Photographers"],
    comfort: "active",
    blurb: "Landmarks, lobby peeks, and skyline geometry.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Midtown towers and Grand Central.",
        minutes: 15,
        options: commonFlex(
          "Chrysler / Empire / GCT architecture walk.",
          "Architect’s lunch nearby.",
          "Skyscraper Museum or MoMA.",
          [{ cat: "SHOPPING", place: "Design store browse." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "Downtown canyon streets.",
        minutes: 35,
        options: commonFlex(
          "Wall Street / Woolworth Building exteriors.",
          "FiDi eats.",
          "9/11 Memorial plaza design.",
          [{ cat: "WATER_ACTIVITY", place: "Harbor for skyline massing." }],
        ),
      },
      {
        label: "Day 3",
        defaultCat: "SIGHTS",
        summary: "Brooklyn vantage points.",
        minutes: 30,
        options: commonFlex(
          "DUMBO framing shots.",
          "Waterfront lunch.",
          "AIA guide tour if available.",
          [{ cat: "FREE_TIME", place: "Shoot freestyle." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-19",
    slug: "nyc-rooftop-golden-hour",
    title: "Rooftop Golden Hour",
    days: 2,
    route: "Views → cocktails → soft morning",
    bestFor: ["Couples", "Celebrations", "Influencers"],
    comfort: "relaxed",
    blurb: "Chase light — legal views, golden hour, one unforgettable night.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Day deck + night rooftop.",
        minutes: 20,
        options: [
          { cat: "SIGHTS", place: "SUMMIT / Edge by day.", viator: "SUMMIT" },
          { cat: "NIGHTLIFE", place: "Rooftop cocktails at golden hour.", viator: "rooftop New York" },
          { cat: "FOOD", place: "Dinner with a view." },
          { cat: "PRIVATE_GROUP_EVENT", place: "Private rooftop toast.", special: true },
          { cat: "RELAX", place: "Spa before the night out." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "RELAX",
        summary: "Slow recovery morning.",
        minutes: 15,
        options: commonFlex(
          "One last viewpoint.",
          "Brunch.",
          "Quiet gallery.",
          [{ cat: "FREE_TIME", place: "Sleep in." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-20",
    slug: "nyc-shopping-soho-fifth",
    title: "Shopping — SoHo to Fifth",
    days: 2,
    route: "SoHo → Fifth Avenue",
    bestFor: ["Shoppers", "Groups"],
    comfort: "balanced",
    blurb: "Cast-iron boutiques by day, flagship Fifth by afternoon.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SHOPPING",
        summary: "SoHo streets.",
        minutes: 30,
        options: [
          { cat: "SHOPPING", place: "SoHo boutique marathon.", viator: "SoHo shopping" },
          { cat: "FOOD", place: "SoHo lunch stops." },
          { cat: "CULTURE", place: "Gallery peek between shops." },
          { cat: "SIGHTS", place: "Cast-iron architecture photos." },
          { cat: "RELAX", place: "Cafe sit-downs between bags." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "SHOPPING",
        summary: "Fifth Avenue flagships.",
        minutes: 20,
        options: commonFlex(
          "Rockefeller exterior.",
          "Midtown lunch.",
          "Window displays as culture.",
          [{ cat: "SHOPPING", place: "Fifth Avenue flagships.", viator: "Fifth Avenue" }],
        ),
      },
    ],
  },
];

const seedsFinal: NycSeed[] = [
  {
    id: "nyc-inspire-21",
    slug: "nyc-spiritual-quiet",
    title: "Spiritual NYC — Quiet Power",
    days: 2,
    route: "Cathedrals → memorials → calm parks",
    bestFor: ["Reflective travel", "Faith & heritage"],
    comfort: "relaxed",
    blurb: "St. Patrick’s, memorials, and spaces that slow the city down.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "RELIGIOUS",
        summary: "Sacred Midtown.",
        minutes: 15,
        options: [
          { cat: "RELIGIOUS", place: "St. Patrick’s Cathedral visit." },
          { cat: "CULTURE", place: "Nearby museum hour." },
          { cat: "SIGHTS", place: "Rockefeller plaza calm stroll." },
          { cat: "FOOD", place: "Quiet lunch nearby." },
          { cat: "RELAX", place: "Evening reflection walk." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "RELIGIOUS",
        summary: "Downtown memorials.",
        minutes: 35,
        options: [
          { cat: "RELIGIOUS", place: "Trinity Church / downtown sacred sites." },
          { cat: "CULTURE", place: "9/11 Memorial (respectful visit).", viator: "9/11 Memorial" },
          { cat: "NATURE", place: "Battery Park quiet corners." },
          { cat: "FREE_TIME", place: "Unstructured stillness." },
          { cat: "FOOD", place: "Simple meal after." },
        ],
      },
    ],
  },
  {
    id: "nyc-inspire-22",
    slug: "nyc-photography-walk",
    title: "Photography Walk Manhattan",
    days: 2,
    route: "Light chases across boroughs",
    bestFor: ["Photographers", "Creators"],
    comfort: "active",
    blurb: "Golden hour routes, reflections, and street stories.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Classic compositions.",
        minutes: 25,
        options: commonFlex(
          "Flatiron → Washington Sq → SoHo textures.",
          "Quick bites between shoots.",
          "Street photography museum stop.",
          [{ cat: "NATURE", place: "Park light at dusk." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "Bridge and water reflections.",
        minutes: 30,
        options: commonFlex(
          "Brooklyn Bridge + DUMBO.",
          "Coffee for cold hands.",
          "ICP or gallery.",
          [{ cat: "WATER_ACTIVITY", place: "Ferry as moving vantage." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-23",
    slug: "nyc-staten-island-ferry-classic",
    title: "Staten Island Ferry Classic",
    days: 1,
    route: "Battery ↔ SI Ferry",
    bestFor: ["Budget", "Views", "Half day"],
    comfort: "relaxed",
    blurb: "Free skyline theater on the water — still one of NYC’s best tricks.",
    daySeeds: [
      {
        label: "Today",
        defaultCat: "WATER_ACTIVITY",
        summary: "Round-trip ferry + downtown soft add-ons.",
        minutes: 35,
        options: [
          { cat: "WATER_ACTIVITY", place: "Staten Island Ferry round trip." },
          { cat: "SIGHTS", place: "Battery Park + skyline photos." },
          { cat: "FOOD", place: "Seaport or FiDi lunch." },
          { cat: "CULTURE", place: "Optional 9/11 plaza." },
          { cat: "FREE_TIME", place: "Just the ferry — enough." },
        ],
      },
    ],
  },
  {
    id: "nyc-inspire-24",
    slug: "nyc-night-owl",
    title: "Night Owl NYC",
    days: 2,
    route: "Late starts, louder finishes",
    bestFor: ["Night owls", "Nightlife", "Groups"],
    comfort: "active",
    blurb: "Sleep in, feast late, chase neon until the trains thin out.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "NIGHTLIFE",
        summary: "Late brunch → late night.",
        minutes: 20,
        options: [
          { cat: "NIGHTLIFE", place: "Club or lounge night.", viator: "New York nightlife" },
          { cat: "FOOD", place: "Late dinner + midnight slice." },
          { cat: "LIVE_ENTERTAINMENT", place: "Late comedy or music." },
          { cat: "SIGHTS", place: "Nighttime observation deck.", viator: "Edge night" },
          { cat: "FREE_TIME", place: "Hotel late checkout energy." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "Recovery eats.",
        minutes: 20,
        options: commonFlex(
          "Easy afternoon wander.",
          "Hangover brunch done right.",
          "Indoor culture only.",
          [{ cat: "RELAX", place: "Spa recovery." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-25",
    slug: "nyc-slow-morning-uws",
    title: "Slow Morning Upper West",
    days: 2,
    route: "UWS + park edge",
    bestFor: ["Relaxed pace", "Families", "Return visitors"],
    comfort: "relaxed",
    blurb: "Bagels, brownstones, and museum mornings without Midtown noise.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "UWS rituals.",
        minutes: 20,
        options: commonFlex(
          "Riverside or park edge walk.",
          "Bagels / classic UWS breakfast.",
          "Natural History or Met edge.",
          [{ cat: "FAMILY", place: "Kid-friendly museum pacing." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Park only if you want.",
        minutes: 15,
        options: commonFlex(
          "Central Park west side.",
          "Another bakery stop.",
          "Lincoln Center exterior.",
          [{ cat: "LIVE_ENTERTAINMENT", place: "Lincoln Center performance if timed.", viator: "Lincoln Center" }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-26",
    slug: "nyc-chinatown-little-italy",
    title: "Chinatown & Little Italy Mix",
    days: 2,
    route: "Canal → Mulberry → LES",
    bestFor: ["Food", "First timers", "Walkers"],
    comfort: "balanced",
    blurb: "Bao, noodles, cannoli — dense blocks of flavor and history.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Chinatown deep tasting.",
        minutes: 30,
        options: [
          { cat: "FOOD", place: "Dumplings, buns, tofu pudding crawl.", viator: "Chinatown food tour" },
          { cat: "CULTURE", place: "Neighborhood history walk." },
          { cat: "SIGHTS", place: "Canal Street energy photos." },
          { cat: "SHOPPING", place: "Tea and pantry shops." },
          { cat: "FREE_TIME", place: "Graze without a map." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "Little Italy into LES.",
        minutes: 30,
        options: commonFlex(
          "Mulberry stroll.",
          "Cannoli + Italian classics.",
          "Tenement Museum nearby.",
          [{ cat: "NIGHTLIFE", place: "LES evening." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-27",
    slug: "nyc-koreatown-late",
    title: "Koreatown Late Night",
    days: 2,
    route: "32nd Street belt",
    bestFor: ["Foodies", "Night owls"],
    comfort: "balanced",
    blurb: "BBQ smoke, karaoke options, and Midtown convenience.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "KTown feast.",
        minutes: 15,
        options: [
          { cat: "FOOD", place: "Korean BBQ + banchan night.", viator: "Koreatown food" },
          { cat: "NIGHTLIFE", place: "Karaoke or late bars." },
          { cat: "SIGHTS", place: "Empire State exterior nearby.", viator: "Empire State" },
          { cat: "SHOPPING", place: "K-beauty and snacks." },
          { cat: "FREE_TIME", place: "Second dinner if brave." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "Midtown day after.",
        minutes: 15,
        options: commonFlex(
          "Observation deck.",
          "Lighter Korean lunch.",
          "MoMA.",
          [{ cat: "RELAX", place: "Easy day." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-28",
    slug: "nyc-girls-trip-glam",
    title: "Girls Trip — Glam Edition",
    days: 3,
    route: "SoHo → rooftops → Broadway",
    bestFor: ["Groups", "Celebrations"],
    comfort: "balanced",
    blurb: "Shops, spas, a show, and one ridiculous view.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SHOPPING",
        summary: "SoHo glam day.",
        minutes: 30,
        options: commonFlex(
          "Photo spots between shops.",
          "Cute lunch.",
          "Gallery pep.",
          [{ cat: "RELAX", place: "Group spa booking.", viator: "spa New York" }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "LIVE_ENTERTAINMENT",
        summary: "Show night.",
        minutes: 15,
        options: [
          { cat: "LIVE_ENTERTAINMENT", place: "Broadway together.", viator: "Broadway" },
          { cat: "FOOD", place: "Pre-theater group dinner." },
          { cat: "NIGHTLIFE", place: "Post-show celebration." },
          { cat: "SIGHTS", place: "Night views.", viator: "SUMMIT" },
          { cat: "PRIVATE_GROUP_EVENT", place: "Private dining room.", special: true },
        ],
      },
      {
        label: "Day 3",
        defaultCat: "SIGHTS",
        summary: "Brunch + one view.",
        minutes: 20,
        options: commonFlex(
          "Final skyline hit.",
          "Celebration brunch.",
          "Easy museum.",
          [{ cat: "FREE_TIME", place: "Souvenir only." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-29",
    slug: "nyc-solo-soft-launch",
    title: "Solo Traveler Soft Launch",
    days: 3,
    route: "Walkable pockets",
    bestFor: ["Solo", "First timers"],
    comfort: "relaxed",
    blurb: "Safe-feeling loops, cafe tables for one, zero FOMO.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Midtown soft icons.",
        minutes: 15,
        options: commonFlex(
          "Bryant Park + library exterior.",
          "Counter lunch.",
          "One museum.",
          [{ cat: "FREE_TIME", place: "Journal in a cafe." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Park alone time.",
        minutes: 20,
        options: commonFlex(
          "Central Park long walk.",
          "Bakery fuel.",
          "Met if curious.",
          [{ cat: "RELAX", place: "Spa hour." }],
        ),
      },
      {
        label: "Day 3",
        defaultCat: "FOOD",
        summary: "Neighborhood tasting alone.",
        minutes: 25,
        options: commonFlex(
          "Village wander.",
          "Solo food crawl.",
          "Small gallery.",
          [{ cat: "LIVE_ENTERTAINMENT", place: "Comedy club for one." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-30",
    slug: "nyc-anniversary-skyline",
    title: "Anniversary Skyline",
    days: 2,
    route: "Views + private dinner",
    bestFor: ["Couples", "Anniversaries"],
    comfort: "relaxed",
    blurb: "One perfect dinner, one perfect view, nothing wasted.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "PRIVATE_GROUP_EVENT",
        summary: "Celebration night.",
        minutes: 20,
        options: [
          { cat: "PRIVATE_GROUP_EVENT", place: "Anniversary tasting menu.", special: true },
          { cat: "SIGHTS", place: "Sunset observation deck.", viator: "Edge" },
          { cat: "NIGHTLIFE", place: "Champagne rooftop." },
          { cat: "FOOD", place: "Iconic NYC dinner." },
          { cat: "RELAX", place: "Couples spa first.", viator: "spa" },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Soft park morning.",
        minutes: 20,
        options: commonFlex(
          "Quiet Conservatory Garden.",
          "Brunch for two.",
          "One gallery.",
          [{ cat: "FREE_TIME", place: "Unplanned wander." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-31",
    slug: "nyc-food-hall-hop",
    title: "Food Hall Hop",
    days: 2,
    route: "Chelsea → Hudson Yards → Brooklyn",
    bestFor: ["Foodies", "Indecisive eaters", "Groups"],
    comfort: "balanced",
    blurb: "Maximum flavor, minimum commitment — graze the city’s best halls.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Chelsea Market + High Line.",
        minutes: 25,
        options: [
          { cat: "FOOD", place: "Chelsea Market full graze.", viator: "Chelsea Market" },
          { cat: "NATURE", place: "High Line digest walk." },
          { cat: "SIGHTS", place: "Whitney exterior / Meatpacking." },
          { cat: "SHOPPING", place: "Market retail." },
          { cat: "FREE_TIME", place: "Second dessert." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "Another hall + borough hop.",
        minutes: 30,
        options: [
          { cat: "FOOD", place: "Time Out Market Brooklyn or Urbanspace.", viator: "food hall New York" },
          { cat: "SIGHTS", place: "Nearby viewpoint." },
          { cat: "WATER_ACTIVITY", place: "Ferry between halls." },
          { cat: "NIGHTLIFE", place: "Late sweets." },
          { cat: "RELAX", place: "Stop after two halls." },
        ],
      },
    ],
  },
  {
    id: "nyc-inspire-32",
    slug: "nyc-live-music-beyond-broadway",
    title: "Live Music Beyond Broadway",
    days: 2,
    route: "Jazz · rock · small rooms",
    bestFor: ["Music lovers", "Night energy"],
    comfort: "balanced",
    blurb: "Village basements, Harlem notes, and rooms where the band is close.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "LIVE_ENTERTAINMENT",
        summary: "Jazz or intimate venue night.",
        minutes: 25,
        options: [
          { cat: "LIVE_ENTERTAINMENT", place: "Jazz club evening.", viator: "jazz New York" },
          { cat: "FOOD", place: "Pre-show dinner nearby." },
          { cat: "NIGHTLIFE", place: "Another set elsewhere." },
          { cat: "CULTURE", place: "Music history walk." },
          { cat: "FREE_TIME", place: "One perfect set only." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "LIVE_ENTERTAINMENT",
        summary: "Matinee or second genre.",
        minutes: 25,
        options: commonFlex(
          "Record shop wander.",
          "Musician’s brunch.",
          "Museum with sound exhibits.",
          [{ cat: "LIVE_ENTERTAINMENT", place: "Second venue.", viator: "live music New York" }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-33",
    slug: "nyc-kids-natural-history",
    title: "Kids + Natural History",
    days: 2,
    route: "AMNH + park",
    bestFor: ["Families", "Science-curious kids"],
    comfort: "relaxed",
    blurb: "Dinosaurs, planetarium magic, and park wiggle room.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FAMILY",
        summary: "Museum deep dive.",
        minutes: 20,
        options: [
          { cat: "FAMILY", place: "AMNH kid pacing.", viator: "Natural History Museum" },
          { cat: "CULTURE", place: "Planetarium if timed.", viator: "Hayden Planetarium" },
          { cat: "FOOD", place: "Simple museum-adjacent meals." },
          { cat: "NATURE", place: "Park run-around after." },
          { cat: "RELAX", place: "Early bedtime." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Park and soft sights.",
        minutes: 20,
        options: commonFlex(
          "Central Park playground circuit.",
          "Ice cream priority.",
          "Second kid museum optional.",
          [{ cat: "FAMILY", place: "Zoo hour.", viator: "Central Park Zoo" }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-34",
    slug: "nyc-chelsea-gallery-crawl",
    title: "Chelsea Gallery Crawl",
    days: 2,
    route: "West Chelsea galleries",
    bestFor: ["Art lovers", "Design"],
    comfort: "balanced",
    blurb: "Warehouse galleries, free openings energy, serious looking.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Gallery blocks.",
        minutes: 25,
        options: [
          { cat: "CULTURE", place: "Chelsea gallery crawl.", viator: "Chelsea galleries" },
          { cat: "FOOD", place: "Gallery-district lunch." },
          { cat: "NATURE", place: "High Line between spaces." },
          { cat: "SHOPPING", place: "Design objects." },
          { cat: "FREE_TIME", place: "Sit with one piece longer." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "CULTURE",
        summary: "Whitney or more rooms.",
        minutes: 25,
        options: commonFlex(
          "Meatpacking wander.",
          "Market snacks.",
          "Whitney Museum.",
          [{ cat: "RELAX", place: "Cafe critique session." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-35",
    slug: "nyc-holiday-lights",
    title: "Holiday Lights Spectacular",
    days: 3,
    route: "Fifth Ave → windows → park lights",
    bestFor: ["Winter travel", "Families", "Couples"],
    comfort: "balanced",
    blurb: "Windows, trees, and cocoa — peak December magic (works off-season as festive Midtown too).",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Fifth Avenue glow.",
        minutes: 15,
        options: commonFlex(
          "Rockefeller tree / plaza lights.",
          "Cocoa and chestnuts energy snacks.",
          "Window displays as art.",
          [{ cat: "SHOPPING", place: "Festive flagships." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "LIVE_ENTERTAINMENT",
        summary: "Show + sparkle.",
        minutes: 15,
        options: [
          { cat: "LIVE_ENTERTAINMENT", place: "Holiday show or classic Broadway.", viator: "Broadway" },
          { cat: "SIGHTS", place: "More lights after curtain." },
          { cat: "FOOD", place: "Festive dinner." },
          { cat: "FAMILY", place: "Kid-friendly light walk." },
          { cat: "RELAX", place: "Hotel fireplace energy." },
        ],
      },
      {
        label: "Day 3",
        defaultCat: "NATURE",
        summary: "Park winter walk.",
        minutes: 20,
        options: commonFlex(
          "Central Park winter paths.",
          "Brunch.",
          "Museum warm-up.",
          [{ cat: "FREE_TIME", place: "Souvenir ornaments only." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-36",
    slug: "nyc-summer-outdoor",
    title: "Summer Outdoor NYC",
    days: 3,
    route: "Parks · piers · ferries",
    bestFor: ["Summer trips", "Outdoors"],
    comfort: "active",
    blurb: "Long light, outdoor movies energy, water whenever you can.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "NATURE",
        summary: "Park all day.",
        minutes: 20,
        options: commonFlex(
          "Central Park picnic marathon.",
          "Outdoor food stands.",
          "Outdoor performance if any.",
          [{ cat: "WATER_ACTIVITY", place: "Evening ferry breeze." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "WATER_ACTIVITY",
        summary: "Harbor and piers.",
        minutes: 30,
        options: [
          { cat: "WATER_ACTIVITY", place: "Harbor cruise or ferry day.", viator: "harbor cruise" },
          { cat: "NATURE", place: "Brooklyn Bridge Park lawn." },
          { cat: "FOOD", place: "Waterfront dinner." },
          { cat: "SIGHTS", place: "Sunset skyline." },
          { cat: "NIGHTLIFE", place: "Outdoor rooftop." },
        ],
      },
      {
        label: "Day 3",
        defaultCat: "SIGHTS",
        summary: "Early sights before heat.",
        minutes: 20,
        options: commonFlex(
          "Early Midtown, AC museums midday.",
          "Ice cream priority.",
          "Indoor culture escape.",
          [{ cat: "RELAX", place: "Pool / hotel cooldown." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-37",
    slug: "nyc-fall-foliage-parks",
    title: "Fall Foliage Parks",
    days: 2,
    route: "Central Park → Brooklyn parks",
    bestFor: ["Fall travel", "Photographers"],
    comfort: "balanced",
    blurb: "Maple light, crisp air, and park paths at their best.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "NATURE",
        summary: "Central Park color.",
        minutes: 20,
        options: commonFlex(
          "Full foliage photo walk.",
          "Warm drinks between loops.",
          "Met after leaves.",
          [{ cat: "FAMILY", place: "Leaf-pile kid time." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Brooklyn green.",
        minutes: 35,
        options: commonFlex(
          "Prospect Park or Bridge Park color.",
          "Neighborhood bakery.",
          "Brooklyn Museum optional.",
          [{ cat: "FREE_TIME", place: "Sit under trees." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-38",
    slug: "nyc-village-history-pride",
    title: "Village History & Pride",
    days: 2,
    route: "West Village heritage",
    bestFor: ["History", "LGBTQ+ travelers", "Culture"],
    comfort: "relaxed",
    blurb: "Stonewall legacy, Village streets, and joyful nights out.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Heritage walk.",
        minutes: 25,
        options: [
          { cat: "CULTURE", place: "Stonewall / Village history walk.", viator: "Greenwich Village tour" },
          { cat: "FOOD", place: "Village restaurants." },
          { cat: "NIGHTLIFE", place: "Celebratory night out." },
          { cat: "SIGHTS", place: "Brownstone photography." },
          { cat: "LIVE_ENTERTAINMENT", place: "Cabaret or queer comedy." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "Brunch and bookstores.",
        minutes: 25,
        options: commonFlex(
          "Hudson River Park.",
          "Iconic Village brunch.",
          "Independent bookstores.",
          [{ cat: "SHOPPING", place: "Pride and indie shops." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-39",
    slug: "nyc-jewish-heritage-les",
    title: "Jewish Heritage — LES",
    days: 2,
    route: "Lower East Side heritage",
    bestFor: ["Heritage travel", "Food history"],
    comfort: "balanced",
    blurb: "Pickles, pastrami lore, synagogues, and tenement memory.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Tenement + tasting.",
        minutes: 25,
        options: [
          { cat: "CULTURE", place: "Tenement Museum.", viator: "Tenement Museum" },
          { cat: "FOOD", place: "Pastrami / pickle classics.", viator: "Lower East Side food" },
          { cat: "RELIGIOUS", place: "Historic synagogue visits." },
          { cat: "SHOPPING", place: "Legacy shops." },
          { cat: "FREE_TIME", place: "Sit with the stories." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "More bites + museum.",
        minutes: 25,
        options: commonFlex(
          "Neighborhood wander.",
          "More LES classics.",
          "Jewish Museum uptown optional.",
          [{ cat: "RELAX", place: "Cafe reflection." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-40",
    slug: "nyc-black-history-harlem",
    title: "Black History Harlem",
    days: 2,
    route: "Harlem heritage",
    bestFor: ["Heritage", "Culture", "Music"],
    comfort: "balanced",
    blurb: "Renaissance streets, institutions, and food that built legends.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Heritage anchors.",
        minutes: 40,
        options: [
          { cat: "CULTURE", place: "Harlem heritage tour.", viator: "Harlem tour" },
          { cat: "FOOD", place: "Soul food institutions.", viator: "Harlem food tour" },
          { cat: "LIVE_ENTERTAINMENT", place: "Apollo / jazz.", viator: "Apollo" },
          { cat: "RELIGIOUS", place: "Historic churches." },
          { cat: "SIGHTS", place: "Brownstone architecture." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "More uptown.",
        minutes: 40,
        options: commonFlex(
          "Marcus Garvey Park views.",
          "Second legendary meal.",
          "Studio Museum.",
          [{ cat: "SHOPPING", place: "Local makers." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-41",
    slug: "nyc-film-locations",
    title: "Film Locations NYC",
    days: 2,
    route: "Movie streets you know",
    bestFor: ["Film fans", "Pop culture"],
    comfort: "balanced",
    blurb: "Stand where the cameras stood — then eat like a local extra.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Manhattan movie mile.",
        minutes: 25,
        options: [
          { cat: "SIGHTS", place: "Film locations walking tour.", viator: "TV and movie tour" },
          { cat: "FOOD", place: "Diner scenes come true." },
          { cat: "CULTURE", place: "Museum of the Moving Image (Queens) optional.", viator: "Museum of the Moving Image" },
          { cat: "SHOPPING", place: "Prop-ish souvenirs." },
          { cat: "FREE_TIME", place: "Re-watch on the hotel bed." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "Bridge & borough cameos.",
        minutes: 30,
        options: commonFlex(
          "Brooklyn Bridge film angles.",
          "DUMBO bites.",
          "More location hunting.",
          [{ cat: "LIVE_ENTERTAINMENT", place: "Broadway — cinema’s cousin." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-42",
    slug: "nyc-coffee-bookstores",
    title: "Coffee & Bookstores",
    days: 2,
    route: "Indie shelves + perfect cups",
    bestFor: ["Readers", "Slow travel", "Solo"],
    comfort: "relaxed",
    blurb: "A literary New York — pages, pour-overs, and park benches.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Bookstore crawl.",
        minutes: 25,
        options: [
          { cat: "CULTURE", place: "Indie bookstore hopping." },
          { cat: "FOOD", place: "Specialty coffee route." },
          { cat: "SIGHTS", place: "NYPL Rose Reading Room exterior/visit." },
          { cat: "RELAX", place: "Read in Bryant Park." },
          { cat: "SHOPPING", place: "Stack of new books." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Park reading day.",
        minutes: 20,
        options: commonFlex(
          "Central Park with a novel.",
          "Bakery chapters.",
          "Poetry reading if scheduled.",
          [{ cat: "FREE_TIME", place: "No agenda — only chapters." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-43",
    slug: "nyc-spa-soft-reset",
    title: "Spa Soft Reset",
    days: 2,
    route: "Recovery-first NYC",
    bestFor: ["Burnout recovery", "Couples", "Luxury"],
    comfort: "relaxed",
    blurb: "The anti-itinerary itinerary — restore, then one gentle highlight.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "RELAX",
        summary: "Spa day.",
        minutes: 15,
        options: [
          { cat: "RELAX", place: "Full spa day.", viator: "spa New York" },
          { cat: "FOOD", place: "Healthy lunch nearby." },
          { cat: "NATURE", place: "Short park exhale." },
          { cat: "FREE_TIME", place: "Hotel robe hours." },
          { cat: "PRIVATE_GROUP_EVENT", place: "Private spa suite.", special: true },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "One soft highlight only.",
        minutes: 20,
        options: commonFlex(
          "One viewpoint — that’s it.",
          "Gentle brunch.",
          "Quiet gallery.",
          [{ cat: "RELAX", place: "Second spa hour." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-44",
    slug: "nyc-private-dinner-celebration",
    title: "Private Dinner Celebration",
    days: 2,
    route: "Celebrate properly",
    bestFor: ["Birthdays", "Proposals", "Milestones"],
    comfort: "relaxed",
    blurb: "The city as backdrop — dinner is the event.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "PRIVATE_GROUP_EVENT",
        summary: "The main event.",
        minutes: 20,
        options: [
          { cat: "PRIVATE_GROUP_EVENT", place: "Private dining room celebration.", special: true },
          { cat: "SIGHTS", place: "Pre-dinner skyline.", viator: "SUMMIT" },
          { cat: "NIGHTLIFE", place: "After-party lounge." },
          { cat: "LIVE_ENTERTAINMENT", place: "Show before dinner.", viator: "Broadway" },
          { cat: "FOOD", place: "Chef’s tasting without private room." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "FOOD",
        summary: "Leftover joy brunch.",
        minutes: 15,
        options: commonFlex(
          "Easy park.",
          "Celebration brunch round two.",
          "Photo museum.",
          [{ cat: "RELAX", place: "Sleep in proud." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-45",
    slug: "nyc-ferry-borough-hop",
    title: "Ferry Borough Hop",
    days: 2,
    route: "East River ferries",
    bestFor: ["Views", "First timers", "Photographers"],
    comfort: "balanced",
    blurb: "Let the water do the commuting — skyline on every crossing.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "WATER_ACTIVITY",
        summary: "Manhattan ↔ Brooklyn ferries.",
        minutes: 30,
        options: [
          { cat: "WATER_ACTIVITY", place: "East River ferry hopping.", viator: "NYC ferry" },
          { cat: "SIGHTS", place: "LIC and DUMBO viewpoints." },
          { cat: "FOOD", place: "Eat wherever you dock." },
          { cat: "NATURE", place: "Waterfront parks between boats." },
          { cat: "FREE_TIME", place: "Ride without getting off twice." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "One neighborhood deep.",
        minutes: 30,
        options: commonFlex(
          "Pick one dock and stay.",
          "Dockside lunch.",
          "Small waterfront culture.",
          [{ cat: "RELAX", place: "Pier sitting." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-46",
    slug: "nyc-upper-east-elegant",
    title: "Upper East Side Elegant",
    days: 2,
    route: "Museum Mile manners",
    bestFor: ["Culture", "Quiet luxury"],
    comfort: "relaxed",
    blurb: "Townhouses, museums, and polished afternoons.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "CULTURE",
        summary: "Museum polish.",
        minutes: 25,
        options: commonFlex(
          "UES architecture stroll.",
          "Proper lunch.",
          "Met or Guggenheim.",
          [{ cat: "SHOPPING", place: "Madison Avenue windows." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Park edge elegance.",
        minutes: 20,
        options: commonFlex(
          "Conservatory Garden.",
          "Brunch.",
          "Second museum.",
          [{ cat: "RELAX", place: "Spa nearby." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-47",
    slug: "nyc-financial-district-history",
    title: "Financial District History",
    days: 2,
    route: "Wall Street → harbor",
    bestFor: ["History", "First timers"],
    comfort: "balanced",
    blurb: "Revolution to skyline — dense downtown stories.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Wall Street core.",
        minutes: 35,
        options: [
          { cat: "SIGHTS", place: "Wall Street / Charging Bull / Fed exteriors.", viator: "Wall Street tour" },
          { cat: "CULTURE", place: "Museum of American Finance or Fraunces Tavern museum energy." },
          { cat: "FOOD", place: "FiDi lunch." },
          { cat: "RELIGIOUS", place: "Trinity Church." },
          { cat: "FREE_TIME", place: "Lobby peeks." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "SIGHTS",
        summary: "Harbor chapter.",
        minutes: 35,
        options: commonFlex(
          "Liberty views.",
          "Seaport eats.",
          "9/11 Memorial.",
          [{ cat: "WATER_ACTIVITY", place: "Short cruise." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-48",
    slug: "nyc-hudson-yards-once",
    title: "Hudson Yards — Once",
    days: 2,
    route: "Yards → High Line → Chelsea",
    bestFor: ["Architecture", "Shopping", "Views"],
    comfort: "balanced",
    blurb: "See the Vessel, shop the sheds, then escape to streets with a pulse.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "SIGHTS",
        summary: "Yards spectacle.",
        minutes: 25,
        options: [
          { cat: "SIGHTS", place: "Vessel + sheds overlook.", viator: "Hudson Yards" },
          { cat: "SHOPPING", place: "Hudson Yards retail." },
          { cat: "FOOD", place: "Yards dining." },
          { cat: "NATURE", place: "High Line exit ramp." },
          { cat: "CULTURE", place: "The Shed programming if live." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Chelsea pulse.",
        minutes: 25,
        options: commonFlex(
          "High Line full walk.",
          "Chelsea Market.",
          "Galleries.",
          [{ cat: "RELAX", place: "Less megastructure, more human scale." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-49",
    slug: "nyc-greenpoint-quiet-cool",
    title: "Greenpoint Quiet Cool",
    days: 2,
    route: "North Brooklyn calm",
    bestFor: ["Return visitors", "Food", "Low-key cool"],
    comfort: "relaxed",
    blurb: "Polish roots, waterfront quiet, fewer selfie sticks.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Greenpoint tastes.",
        minutes: 40,
        options: commonFlex(
          "Transmitter Park skyline.",
          "Neighborhood restaurants.",
          "Indie shops as culture.",
          [{ cat: "NIGHTLIFE", place: "Low-key bar." }],
        ),
      },
      {
        label: "Day 2",
        defaultCat: "NATURE",
        summary: "Waterfront slow.",
        minutes: 40,
        options: commonFlex(
          "Long pier sit.",
          "Bakery morning.",
          "Ferry to Manhattan optional.",
          [{ cat: "FREE_TIME", place: "Do almost nothing." }],
        ),
      },
    ],
  },
  {
    id: "nyc-inspire-50",
    slug: "nyc-astoria-greek-arts",
    title: "Astoria Greek & Arts",
    days: 2,
    route: "Astoria · Museum of the Moving Image",
    bestFor: ["Foodies", "Film fans", "Outer-borough explorers"],
    comfort: "balanced",
    blurb: "Hellenic feasts, film museum geekery, and a borough that feels lived-in.",
    daySeeds: [
      {
        label: "Day 1",
        defaultCat: "FOOD",
        summary: "Astoria feast.",
        minutes: 45,
        options: [
          { cat: "FOOD", place: "Greek feast in Astoria.", viator: "Astoria food" },
          { cat: "CULTURE", place: "Museum of the Moving Image.", viator: "Museum of the Moving Image" },
          { cat: "SIGHTS", place: "Neighborhood street life." },
          { cat: "NIGHTLIFE", place: "Beer gardens / casual night." },
          { cat: "FREE_TIME", place: "Second dessert." },
        ],
      },
      {
        label: "Day 2",
        defaultCat: "CULTURE",
        summary: "More Astoria or LIC hop.",
        minutes: 45,
        options: commonFlex(
          "LIC skyline add-on.",
          "Another legendary meal.",
          "More Moving Image if needed.",
          [{ cat: "WATER_ACTIVITY", place: "Ferry toward Manhattan." }],
        ),
      },
    ],
  },
];

export const nycInspireTemplates: TripTemplate[] = [
  ...seeds,
  ...seedsContinued,
  ...seedsFinal,
].map((seed, i) => nyc(seed, i));
