import type { TourInterest } from "@/lib/tour-types";

/** Starter + future operator-published tours across the USA. */
export type CatalogTour = {
  slug: string;
  citySlug: string;
  cityName: string;
  stateCode: string;
  title: string;
  duration: string;
  meetup: string;
  priceFrom: string;
  joinable: boolean;
  interest: TourInterest;
  summary: string;
  time: string;
  timeLabel: string;
  schedule: "fixed" | "flexible" | "rolling";
  weekdays: number[];
  spacesDefault: number;
  /** starter = ToursIWant seed inventory; operator = live operator listing later */
  source: "starter" | "operator";
};

export type TourMetro = {
  slug: string;
  name: string;
  stateCode: string;
  region: string;
};

export const tourMetros: TourMetro[] = [
  { slug: "new-york", name: "New York", stateCode: "NY", region: "Northeast" },
  { slug: "los-angeles", name: "Los Angeles", stateCode: "CA", region: "West" },
  { slug: "las-vegas", name: "Las Vegas", stateCode: "NV", region: "West" },
  { slug: "miami", name: "Miami", stateCode: "FL", region: "South" },
  { slug: "orlando", name: "Orlando", stateCode: "FL", region: "South" },
  { slug: "chicago", name: "Chicago", stateCode: "IL", region: "Midwest" },
  {
    slug: "san-francisco",
    name: "San Francisco",
    stateCode: "CA",
    region: "West",
  },
  {
    slug: "washington-dc",
    name: "Washington DC",
    stateCode: "DC",
    region: "Northeast",
  },
  { slug: "boston", name: "Boston", stateCode: "MA", region: "Northeast" },
  {
    slug: "new-orleans",
    name: "New Orleans",
    stateCode: "LA",
    region: "South",
  },
  { slug: "seattle", name: "Seattle", stateCode: "WA", region: "West" },
  { slug: "houston", name: "Houston", stateCode: "TX", region: "South" },
  { slug: "dallas", name: "Dallas", stateCode: "TX", region: "South" },
  { slug: "atlanta", name: "Atlanta", stateCode: "GA", region: "South" },
  { slug: "san-diego", name: "San Diego", stateCode: "CA", region: "West" },
  {
    slug: "philadelphia",
    name: "Philadelphia",
    stateCode: "PA",
    region: "Northeast",
  },
  { slug: "honolulu", name: "Honolulu", stateCode: "HI", region: "West" },
  { slug: "nashville", name: "Nashville", stateCode: "TN", region: "South" },
  { slug: "denver", name: "Denver", stateCode: "CO", region: "West" },
  { slug: "phoenix", name: "Phoenix", stateCode: "AZ", region: "West" },
];

const daily = [0, 1, 2, 3, 4, 5, 6];
const weekdays = [1, 2, 3, 4, 5];
const weekends = [0, 5, 6];

function t(
  partial: Omit<CatalogTour, "source" | "schedule" | "weekdays" | "spacesDefault" | "joinable"> &
    Partial<
      Pick<
        CatalogTour,
        "source" | "schedule" | "weekdays" | "spacesDefault" | "joinable"
      >
    >,
): CatalogTour {
  return {
    source: "starter",
    schedule: "fixed",
    weekdays: daily,
    spacesDefault: 8,
    joinable: true,
    ...partial,
  };
}

/** NYC starter set — keeps existing slugs so live links still work. */
const newYorkTours: CatalogTour[] = [
  t({
    slug: "lower-manhattan-highlights",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Lower Manhattan highlights",
    time: "10:30",
    timeLabel: "10:30 a.m.",
    duration: "3.5 hours",
    meetup: "Battery Park",
    priceFrom: "$65",
    interest: "City highlights",
    summary:
      "Shared walking tour of Lower Manhattan landmarks. Meet at Battery Park.",
    weekdays: [1, 2, 3, 4, 5, 6],
  }),
  t({
    slug: "brooklyn-food-crawl",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Brooklyn food crawl",
    time: "13:00",
    timeLabel: "1:00 p.m.",
    duration: "4 hours",
    meetup: "DUMBO waterfront",
    priceFrom: "$89",
    interest: "Food & markets",
    summary:
      "Shared food crawl through Brooklyn. Meet at the DUMBO waterfront.",
    weekdays: [2, 4, 6],
    spacesDefault: 6,
  }),
  t({
    slug: "midtown-central-park-driver",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Private Midtown & Central Park driver",
    time: "",
    timeLabel: "Flexible",
    duration: "2–6 hours",
    meetup: "Your hotel",
    priceFrom: "$180",
    joinable: false,
    interest: "Private driver",
    summary:
      "Private driver for Midtown and Central Park. Pickup at your hotel.",
    schedule: "flexible",
    weekdays: [],
    spacesDefault: 4,
  }),
  t({
    slug: "jfk-manhattan-transfer",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "JFK → Manhattan shared transfer",
    time: "",
    timeLabel: "Rolling",
    duration: "~75 min",
    meetup: "JFK terminals",
    priceFrom: "$45",
    interest: "Airport / hotel transfer",
    summary: "Shared van from JFK into Manhattan hotel drop belt.",
    schedule: "rolling",
    weekdays: [],
    spacesDefault: 6,
  }),
  t({
    slug: "harlem-gospel-afternoon",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Harlem gospel afternoon",
    time: "11:00",
    timeLabel: "11:00 a.m.",
    duration: "3 hours",
    meetup: "125th Street",
    priceFrom: "$75",
    interest: "Neighborhood walk",
    summary: "Harlem culture walk with gospel service window on Sundays.",
    weekdays: [0],
  }),
  t({
    slug: "statue-ellis-half-day",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Statue of Liberty & Ellis Island half-day",
    time: "09:00",
    timeLabel: "9:00 a.m.",
    duration: "5 hours",
    meetup: "Battery Park ferry",
    priceFrom: "$99",
    interest: "City highlights",
    summary:
      "Ferry to Liberty Island and Ellis Island with guided context and photo time.",
    weekdays: daily,
    spacesDefault: 12,
  }),
  t({
    slug: "met-museum-highlights",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "The Met Museum highlights tour",
    time: "10:00",
    timeLabel: "10:00 a.m.",
    duration: "2.5 hours",
    meetup: "Met front steps",
    priceFrom: "$55",
    interest: "Museums & culture",
    summary: "Guided highlights inside The Metropolitan Museum of Art.",
    weekdays: [1, 2, 3, 4, 5, 6],
  }),
  t({
    slug: "soho-nolita-food",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "SoHo & Nolita food walk",
    time: "12:00",
    timeLabel: "12:00 p.m.",
    duration: "3 hours",
    meetup: "Houston Street",
    priceFrom: "$79",
    interest: "Food & markets",
    summary: "Boutique bites through SoHo and Nolita streets.",
    weekdays: [3, 5, 6],
  }),
  t({
    slug: "broadway-night-lights",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Broadway lights & Times Square evening",
    time: "19:00",
    timeLabel: "7:00 p.m.",
    duration: "2.5 hours",
    meetup: "Times Square",
    priceFrom: "$49",
    interest: "Nightlife",
    summary: "Evening walk of Midtown lights, marquees, and photo stops.",
    weekdays: daily,
  }),
  t({
    slug: "chinatown-little-italy",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Chinatown & Little Italy walking tour",
    time: "14:00",
    timeLabel: "2:00 p.m.",
    duration: "3 hours",
    meetup: "Canal Street",
    priceFrom: "$59",
    interest: "Food & markets",
    summary: "Neighborhood walk with dumpling and bakery culture stops.",
    weekdays: [1, 3, 5, 6],
  }),
  t({
    slug: "williamsburg-street-art",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Williamsburg street art & coffee",
    time: "11:00",
    timeLabel: "11:00 a.m.",
    duration: "3 hours",
    meetup: "Bedford Avenue",
    priceFrom: "$55",
    interest: "Neighborhood walk",
    summary: "Murals, coffee, and Brooklyn creative-scene streets.",
    weekdays: [2, 4, 6],
  }),
  t({
    slug: "nyc-night-photography",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "NYC night photography walk",
    time: "20:00",
    timeLabel: "8:00 p.m.",
    duration: "2.5 hours",
    meetup: "Brooklyn Bridge walkway",
    priceFrom: "$69",
    interest: "Nightlife",
    summary: "Skyline and bridge night shots with a photo-minded guide.",
    weekdays: [4, 5, 6],
  }),
  t({
    slug: "cruise-shore-lower-manhattan",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Cruise shore: Lower Manhattan express",
    time: "09:30",
    timeLabel: "9:30 a.m.",
    duration: "4 hours",
    meetup: "Cruise terminal",
    priceFrom: "$120",
    interest: "Cruise shore excursion",
    summary: "Shore-safe Lower Manhattan loop timed to all-aboard.",
    weekdays: daily,
  }),
  t({
    slug: "lga-manhattan-transfer",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "LaGuardia → Manhattan shared transfer",
    time: "",
    timeLabel: "Rolling",
    duration: "~60 min",
    meetup: "LGA terminals",
    priceFrom: "$40",
    interest: "Airport / hotel transfer",
    summary: "Shared transfer from LGA into Manhattan.",
    schedule: "rolling",
    weekdays: [],
  }),
  t({
    slug: "ewr-manhattan-transfer",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Newark → Manhattan shared transfer",
    time: "",
    timeLabel: "Rolling",
    duration: "~70 min",
    meetup: "EWR terminals",
    priceFrom: "$42",
    interest: "Airport / hotel transfer",
    summary: "Shared transfer from Newark into Manhattan hotels.",
    schedule: "rolling",
    weekdays: [],
  }),
  t({
    slug: "private-brooklyn-day",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Private Brooklyn day with driver",
    time: "",
    timeLabel: "Flexible",
    duration: "6 hours",
    meetup: "Your hotel",
    priceFrom: "$320",
    joinable: false,
    interest: "Private driver",
    summary: "Private Brooklyn loop — DUMBO, parks, food stops on your clock.",
    schedule: "flexible",
    weekdays: [],
  }),
  t({
    slug: "high-line-chelsea",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "High Line & Chelsea galleries",
    time: "15:00",
    timeLabel: "3:00 p.m.",
    duration: "2.5 hours",
    meetup: "High Line Gansevoort",
    priceFrom: "$45",
    interest: "Museums & culture",
    summary: "Elevated park walk plus Chelsea gallery corridor.",
    weekdays: [2, 3, 4, 5, 6],
  }),
  t({
    slug: "queens-night-market",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Queens Night Market food evening",
    time: "18:30",
    timeLabel: "6:30 p.m.",
    duration: "3 hours",
    meetup: "Flushing Meadows",
    priceFrom: "$39",
    interest: "Food & markets",
    summary: "Guided tasting evening at Queens Night Market (seasonal nights).",
    weekdays: [6],
  }),
  t({
    slug: "yacht-sunset-harbor",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "NYC harbor yacht sunset",
    time: "18:00",
    timeLabel: "6:00 p.m.",
    duration: "2 hours",
    meetup: "Harbor pier",
    priceFrom: "$89",
    interest: "City highlights",
    summary: "Sunset harbor cruise past skyline and bridges.",
    weekdays: [4, 5, 6],
  }),
  t({
    slug: "nyc-hop-on-bus-day",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Hop-on hop-off double-decker day pass",
    time: "09:00",
    timeLabel: "9:00 a.m.",
    duration: "All day",
    meetup: "Times Square / Midtown stops",
    priceFrom: "$59",
    interest: "City highlights",
    summary:
      "Day ticket style hop-on hop-off loops — board near Midtown hotels and major sights.",
    weekdays: daily,
    spacesDefault: 20,
  }),
  t({
    slug: "custom-nyc-request",
    citySlug: "new-york",
    cityName: "New York",
    stateCode: "NY",
    title: "Custom New York day (request)",
    time: "",
    timeLabel: "On request",
    duration: "Your call",
    meetup: "Your hotel",
    priceFrom: "Quote",
    joinable: false,
    interest: "Something custom",
    summary: "Describe the day — operators send personalised quotes.",
    schedule: "flexible",
    weekdays: [],
  }),
];

function cityBlock(
  citySlug: string,
  cityName: string,
  stateCode: string,
  items: Array<
    Omit<
      CatalogTour,
      | "citySlug"
      | "cityName"
      | "stateCode"
      | "source"
      | "schedule"
      | "weekdays"
      | "spacesDefault"
      | "joinable"
    > &
      Partial<
        Pick<
          CatalogTour,
          "schedule" | "weekdays" | "spacesDefault" | "joinable" | "source"
        >
      >
  >,
): CatalogTour[] {
  return items.map((item) =>
    t({
      ...item,
      citySlug,
      cityName,
      stateCode,
    }),
  );
}

const usaCityTours: CatalogTour[] = [
  ...cityBlock("los-angeles", "Los Angeles", "CA", [
    {
      slug: "la-hollywood-sign-viewpoints",
      title: "Hollywood Sign viewpoints & Walk of Fame",
      time: "10:00",
      timeLabel: "10:00 a.m.",
      duration: "3.5 hours",
      meetup: "Hollywood Boulevard",
      priceFrom: "$69",
      interest: "City highlights",
      summary: "Classic Hollywood photo stops, Walk of Fame, and sign viewpoints.",
    },
    {
      slug: "la-studio-backlot-day",
      title: "Studio backlot / studio tour day",
      time: "09:30",
      timeLabel: "9:30 a.m.",
      duration: "5 hours",
      meetup: "Studio gate / hotel pickup",
      priceFrom: "$129",
      interest: "Museums & culture",
      summary:
        "Studio-style backlot experience day — sets, soundstage stories, photo time.",
      spacesDefault: 14,
    },
    {
      slug: "la-santa-monica-venice",
      title: "Santa Monica & Venice Beach half-day",
      time: "13:00",
      timeLabel: "1:00 p.m.",
      duration: "4 hours",
      meetup: "Santa Monica Pier",
      priceFrom: "$59",
      interest: "Neighborhood walk",
      summary: "Pier, boardwalk, Muscle Beach energy, and Pacific photo stops.",
    },
    {
      slug: "la-food-truck-crawl",
      title: "LA food truck & taco crawl",
      time: "17:30",
      timeLabel: "5:30 p.m.",
      duration: "3 hours",
      meetup: "Arts District",
      priceFrom: "$79",
      interest: "Food & markets",
      summary: "Guided evening tastes across iconic LA casual food stops.",
      weekdays: [3, 4, 5, 6],
    },
    {
      slug: "la-griffith-observatory-sunset",
      title: "Griffith Observatory sunset",
      time: "16:30",
      timeLabel: "4:30 p.m.",
      duration: "3 hours",
      meetup: "Griffith Observatory",
      priceFrom: "$55",
      interest: "City highlights",
      summary: "Observatory decks and LA basin sunset views.",
      weekdays: weekends,
    },
    {
      slug: "lax-hotel-transfer",
      title: "LAX → hotel shared transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~60–90 min",
      meetup: "LAX terminals",
      priceFrom: "$49",
      interest: "Airport / hotel transfer",
      summary: "Shared airport transfer into Hollywood / Santa Monica / Downtown belts.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("las-vegas", "Las Vegas", "NV", [
    {
      slug: "vegas-strip-highlights-night",
      title: "Las Vegas Strip night highlights",
      time: "19:30",
      timeLabel: "7:30 p.m.",
      duration: "3 hours",
      meetup: "Bellagio fountains",
      priceFrom: "$49",
      interest: "Nightlife",
      summary: "Fountains, neon corridors, and marquee photo stops after dark.",
    },
    {
      slug: "vegas-red-rock-half-day",
      title: "Red Rock Canyon half-day",
      time: "08:00",
      timeLabel: "8:00 a.m.",
      duration: "5 hours",
      meetup: "Strip hotel pickup",
      priceFrom: "$99",
      interest: "City highlights",
      summary: "Scenic loop outside the Strip — viewpoints and desert light.",
      weekdays: daily,
    },
    {
      slug: "vegas-grand-canyon-day",
      title: "Grand Canyon day trip from Vegas",
      time: "06:00",
      timeLabel: "6:00 a.m.",
      duration: "12–14 hours",
      meetup: "Strip hotel pickup",
      priceFrom: "$159",
      interest: "City highlights",
      summary: "Full-day canyon excursion with hotel pickup corridor.",
      spacesDefault: 16,
    },
    {
      slug: "vegas-downtown-fremont",
      title: "Downtown Fremont Street evening",
      time: "20:00",
      timeLabel: "8:00 p.m.",
      duration: "2.5 hours",
      meetup: "Fremont Street Experience",
      priceFrom: "$39",
      interest: "Nightlife",
      summary: "Canopy lights, classic Vegas downtown energy, guided photo route.",
      weekdays: [4, 5, 6],
    },
    {
      slug: "las-hotel-transfer",
      title: "LAS → Strip hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~30–45 min",
      meetup: "LAS airport",
      priceFrom: "$25",
      interest: "Airport / hotel transfer",
      summary: "Shared airport shuttle into Strip hotel zone.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("miami", "Miami", "FL", [
    {
      slug: "miami-south-beach-art-deco",
      title: "South Beach Art Deco walking tour",
      time: "10:00",
      timeLabel: "10:00 a.m.",
      duration: "2.5 hours",
      meetup: "Ocean Drive",
      priceFrom: "$45",
      interest: "Neighborhood walk",
      summary: "Pastel façades, Deco history, and beach corridor photo stops.",
    },
    {
      slug: "miami-little-havana-food",
      title: "Little Havana food & culture walk",
      time: "14:00",
      timeLabel: "2:00 p.m.",
      duration: "3 hours",
      meetup: "Calle Ocho",
      priceFrom: "$69",
      interest: "Food & markets",
      summary: "Cuban coffee, street culture, and tasting stops in Little Havana.",
    },
    {
      slug: "miami-wynwood-walls",
      title: "Wynwood Walls street art tour",
      time: "11:00",
      timeLabel: "11:00 a.m.",
      duration: "2 hours",
      meetup: "Wynwood Walls",
      priceFrom: "$39",
      interest: "Museums & culture",
      summary: "Murals and gallery blocks with a local art-minded guide.",
    },
    {
      slug: "miami-everglades-half-day",
      title: "Everglades airboat half-day",
      time: "08:30",
      timeLabel: "8:30 a.m.",
      duration: "4.5 hours",
      meetup: "Hotel pickup / Everglades gate",
      priceFrom: "$79",
      interest: "City highlights",
      summary: "Airboat run and wildlife viewing outside the city.",
    },
    {
      slug: "mia-hotel-transfer",
      title: "MIA → South Beach / Downtown transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~35–55 min",
      meetup: "MIA airport",
      priceFrom: "$35",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into South Beach or Downtown Miami hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("orlando", "Orlando", "FL", [
    {
      slug: "orlando-theme-park-transfer",
      title: "Hotel ↔ theme park shared transfer",
      time: "08:00",
      timeLabel: "8:00 a.m.",
      duration: "Round-trip day",
      meetup: "Your Orlando hotel",
      priceFrom: "$40",
      interest: "Airport / hotel transfer",
      summary: "Shared shuttles between hotel corridor and major park gates.",
      weekdays: daily,
      spacesDefault: 12,
    },
    {
      slug: "orlando-disney-area-highlights",
      title: "Disney Springs / resort area evening",
      time: "17:00",
      timeLabel: "5:00 p.m.",
      duration: "3 hours",
      meetup: "Disney Springs",
      priceFrom: "$49",
      interest: "Nightlife",
      summary: "Resort-area evening stroll, dining belt, and photo stops.",
    },
    {
      slug: "orlando-kennedy-space-day",
      title: "Kennedy Space Center day trip",
      time: "07:30",
      timeLabel: "7:30 a.m.",
      duration: "10 hours",
      meetup: "Orlando hotel pickup",
      priceFrom: "$149",
      interest: "Museums & culture",
      summary: "Full-day Space Coast excursion with hotel pickup.",
      spacesDefault: 16,
    },
    {
      slug: "orlando-food-international-drive",
      title: "International Drive food evening",
      time: "18:00",
      timeLabel: "6:00 p.m.",
      duration: "3 hours",
      meetup: "I-Drive",
      priceFrom: "$59",
      interest: "Food & markets",
      summary: "Casual tasting walk along the I-Drive visitor corridor.",
      weekdays: [4, 5, 6],
    },
    {
      slug: "mco-hotel-transfer",
      title: "MCO → hotel shared transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~40–60 min",
      meetup: "MCO airport",
      priceFrom: "$30",
      interest: "Airport / hotel transfer",
      summary: "Shared airport transfer into Orlando hotel corridors.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("chicago", "Chicago", "IL", [
    {
      slug: "chicago-architecture-river",
      title: "Chicago architecture river cruise",
      time: "11:00",
      timeLabel: "11:00 a.m.",
      duration: "1.5 hours",
      meetup: "Chicago Riverwalk",
      priceFrom: "$55",
      interest: "City highlights",
      summary: "River architecture storytelling past downtown landmarks.",
    },
    {
      slug: "chicago-millennium-art",
      title: "Millennium Park & Art Institute highlights",
      time: "10:30",
      timeLabel: "10:30 a.m.",
      duration: "3 hours",
      meetup: "Cloud Gate / Bean",
      priceFrom: "$65",
      interest: "Museums & culture",
      summary: "Park icons plus curated Art Institute highlights.",
    },
    {
      slug: "chicago-deep-dish-food",
      title: "Deep dish & neighborhood food walk",
      time: "12:30",
      timeLabel: "12:30 p.m.",
      duration: "3 hours",
      meetup: "River North",
      priceFrom: "$79",
      interest: "Food & markets",
      summary: "Classic Chicago bites with neighborhood context.",
    },
    {
      slug: "chicago-navy-pier-evening",
      title: "Navy Pier evening stroll",
      time: "18:30",
      timeLabel: "6:30 p.m.",
      duration: "2 hours",
      meetup: "Navy Pier",
      priceFrom: "$35",
      interest: "Nightlife",
      summary: "Lakefront evening walk and skyline photo windows.",
      weekdays: [4, 5, 6],
    },
    {
      slug: "ord-hotel-transfer",
      title: "O’Hare → downtown hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~45–70 min",
      meetup: "ORD airport",
      priceFrom: "$38",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown / River North hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("san-francisco", "San Francisco", "CA", [
    {
      slug: "sf-golden-gate-viewpoint",
      title: "Golden Gate Bridge viewpoints",
      time: "09:30",
      timeLabel: "9:30 a.m.",
      duration: "3 hours",
      meetup: "Welcome Center / hotel pickup",
      priceFrom: "$59",
      interest: "City highlights",
      summary: "Bridge vistas, photo stops, and Presidio / Marin overlooks.",
    },
    {
      slug: "sf-alcatraz-day",
      title: "Alcatraz Island ferry day",
      time: "09:00",
      timeLabel: "9:00 a.m.",
      duration: "4–5 hours",
      meetup: "Pier 33",
      priceFrom: "$99",
      interest: "City highlights",
      summary: "Ferry to Alcatraz with timed entry window and audio context.",
      spacesDefault: 12,
    },
    {
      slug: "sf-chinatown-northbeach",
      title: "Chinatown & North Beach walk",
      time: "14:00",
      timeLabel: "2:00 p.m.",
      duration: "3 hours",
      meetup: "Grant Avenue",
      priceFrom: "$49",
      interest: "Neighborhood walk",
      summary: "Two classic neighborhoods — food smells, murals, and hills.",
    },
    {
      slug: "sf-muir-woods-half-day",
      title: "Muir Woods half-day",
      time: "08:00",
      timeLabel: "8:00 a.m.",
      duration: "5 hours",
      meetup: "Union Square pickup",
      priceFrom: "$89",
      interest: "City highlights",
      summary: "Redwood grove half-day with hotel corridor pickup.",
    },
    {
      slug: "sfo-hotel-transfer",
      title: "SFO → downtown hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~35–55 min",
      meetup: "SFO airport",
      priceFrom: "$36",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown / Union Square hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("washington-dc", "Washington DC", "DC", [
    {
      slug: "dc-monuments-night",
      title: "DC monuments by night",
      time: "19:30",
      timeLabel: "7:30 p.m.",
      duration: "3 hours",
      meetup: "Lincoln Memorial",
      priceFrom: "$49",
      interest: "City highlights",
      summary: "Illuminated memorials loop after dark.",
    },
    {
      slug: "dc-capitol-mall-walk",
      title: "Capitol & National Mall highlights",
      time: "10:00",
      timeLabel: "10:00 a.m.",
      duration: "3.5 hours",
      meetup: "Smithsonian Metro area",
      priceFrom: "$55",
      interest: "Museums & culture",
      summary: "Mall museums belt and capitol vista walking tour.",
    },
    {
      slug: "dc-georgetown-food",
      title: "Georgetown food & waterfront walk",
      time: "12:00",
      timeLabel: "12:00 p.m.",
      duration: "3 hours",
      meetup: "M Street",
      priceFrom: "$69",
      interest: "Food & markets",
      summary: "Georgetown streets, waterfront, and tasting stops.",
    },
    {
      slug: "dca-hotel-transfer",
      title: "Reagan National → hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~25–40 min",
      meetup: "DCA airport",
      priceFrom: "$32",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown DC / Georgetown hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("boston", "Boston", "MA", [
    {
      slug: "boston-freedom-trail",
      title: "Freedom Trail walking tour",
      time: "10:00",
      timeLabel: "10:00 a.m.",
      duration: "3 hours",
      meetup: "Boston Common",
      priceFrom: "$49",
      interest: "City highlights",
      summary: "Revolutionary War landmarks along the classic red-brick trail.",
    },
    {
      slug: "boston-north-end-food",
      title: "North End Italian food walk",
      time: "14:00",
      timeLabel: "2:00 p.m.",
      duration: "3 hours",
      meetup: "Hanover Street",
      priceFrom: "$79",
      interest: "Food & markets",
      summary: "Cannoli, pizza, and North End stories.",
    },
    {
      slug: "boston-harbor-cruise",
      title: "Boston Harbor sightseeing cruise",
      time: "15:00",
      timeLabel: "3:00 p.m.",
      duration: "1.5 hours",
      meetup: "Long Wharf",
      priceFrom: "$45",
      interest: "City highlights",
      summary: "Harbor islands and skyline from the water.",
    },
    {
      slug: "bos-hotel-transfer",
      title: "Logan → downtown hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~20–35 min",
      meetup: "BOS airport",
      priceFrom: "$30",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown / Back Bay hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("new-orleans", "New Orleans", "LA", [
    {
      slug: "nola-french-quarter-walk",
      title: "French Quarter history walk",
      time: "10:30",
      timeLabel: "10:30 a.m.",
      duration: "2.5 hours",
      meetup: "Jackson Square",
      priceFrom: "$45",
      interest: "Neighborhood walk",
      summary: "Courtyards, Creole history, and Quarter street life.",
    },
    {
      slug: "nola-jazz-evening",
      title: "Frenchmen Street jazz evening",
      time: "20:00",
      timeLabel: "8:00 p.m.",
      duration: "3 hours",
      meetup: "Frenchmen Street",
      priceFrom: "$59",
      interest: "Nightlife",
      summary: "Live jazz corridor evening with local listening tips.",
      weekdays: [4, 5, 6],
    },
    {
      slug: "nola-food-garden-district",
      title: "Garden District & food tasting",
      time: "13:00",
      timeLabel: "1:00 p.m.",
      duration: "3.5 hours",
      meetup: "St. Charles Avenue",
      priceFrom: "$79",
      interest: "Food & markets",
      summary: "Mansions, streetcars, and New Orleans flavors.",
    },
    {
      slug: "msy-hotel-transfer",
      title: "MSY → French Quarter hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~30–45 min",
      meetup: "MSY airport",
      priceFrom: "$35",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into French Quarter / CBD hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("seattle", "Seattle", "WA", [
    {
      slug: "seattle-pike-place",
      title: "Pike Place Market food tour",
      time: "10:00",
      timeLabel: "10:00 a.m.",
      duration: "3 hours",
      meetup: "Pike Place Market",
      priceFrom: "$75",
      interest: "Food & markets",
      summary: "Market tastings, fish tosses, and waterfront views.",
    },
    {
      slug: "seattle-space-needle-area",
      title: "Seattle Center & Space Needle area",
      time: "14:00",
      timeLabel: "2:00 p.m.",
      duration: "2.5 hours",
      meetup: "Seattle Center",
      priceFrom: "$49",
      interest: "City highlights",
      summary: "Iconic Seattle Center corridor and skyline photo stops.",
    },
    {
      slug: "seattle-underground-tour",
      title: "Pioneer Square underground tour",
      time: "11:00",
      timeLabel: "11:00 a.m.",
      duration: "2 hours",
      meetup: "Pioneer Square",
      priceFrom: "$35",
      interest: "Museums & culture",
      summary: "Below-street Seattle history in Pioneer Square.",
    },
    {
      slug: "sea-hotel-transfer",
      title: "SEA → downtown hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~35–50 min",
      meetup: "SEA airport",
      priceFrom: "$34",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown Seattle hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("houston", "Houston", "TX", [
    {
      slug: "houston-museum-district",
      title: "Museum District highlights",
      time: "10:30",
      timeLabel: "10:30 a.m.",
      duration: "3 hours",
      meetup: "Museum District",
      priceFrom: "$49",
      interest: "Museums & culture",
      summary: "Curated museum corridor walk for first-time Houston visitors.",
    },
    {
      slug: "houston-spacecenter-day",
      title: "Space Center Houston day",
      time: "08:30",
      timeLabel: "8:30 a.m.",
      duration: "7 hours",
      meetup: "Hotel pickup",
      priceFrom: "$119",
      interest: "Museums & culture",
      summary: "NASA visitor experience day with hotel pickup.",
    },
    {
      slug: "iah-hotel-transfer",
      title: "IAH → downtown hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~40–60 min",
      meetup: "IAH airport",
      priceFrom: "$36",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown / Museum District hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("dallas", "Dallas", "TX", [
    {
      slug: "dallas-sixth-floor-dealey",
      title: "Dealey Plaza & downtown history walk",
      time: "10:00",
      timeLabel: "10:00 a.m.",
      duration: "2.5 hours",
      meetup: "Dealey Plaza",
      priceFrom: "$45",
      interest: "City highlights",
      summary: "Downtown Dallas history corridor including Dealey Plaza context.",
    },
    {
      slug: "dallas-fort-worth-stockyards",
      title: "Fort Worth Stockyards half-day",
      time: "13:00",
      timeLabel: "1:00 p.m.",
      duration: "4.5 hours",
      meetup: "Hotel pickup",
      priceFrom: "$79",
      interest: "Neighborhood walk",
      summary: "Western heritage Stockyards visit from Dallas hotels.",
    },
    {
      slug: "dfw-hotel-transfer",
      title: "DFW → Dallas hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~35–55 min",
      meetup: "DFW airport",
      priceFrom: "$38",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown Dallas / Uptown hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("atlanta", "Atlanta", "GA", [
    {
      slug: "atlanta-martin-luther-king",
      title: "MLK National Historical Park walk",
      time: "10:00",
      timeLabel: "10:00 a.m.",
      duration: "2.5 hours",
      meetup: "Sweet Auburn",
      priceFrom: "$39",
      interest: "Museums & culture",
      summary: "Civil rights history walk in the Sweet Auburn corridor.",
    },
    {
      slug: "atlanta-world-of-coke-aquarium",
      title: "Centennial Olympic Park icons",
      time: "13:00",
      timeLabel: "1:00 p.m.",
      duration: "3 hours",
      meetup: "Centennial Olympic Park",
      priceFrom: "$55",
      interest: "City highlights",
      summary: "Park belt orientation for Aquarium / Coke / CNN area visitors.",
    },
    {
      slug: "atl-hotel-transfer",
      title: "ATL → downtown hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~30–50 min",
      meetup: "ATL airport",
      priceFrom: "$34",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown / Midtown Atlanta hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("san-diego", "San Diego", "CA", [
    {
      slug: "sd-gaslamp-evening",
      title: "Gaslamp Quarter evening walk",
      time: "18:30",
      timeLabel: "6:30 p.m.",
      duration: "2 hours",
      meetup: "Gaslamp Quarter",
      priceFrom: "$35",
      interest: "Nightlife",
      summary: "Historic Gaslamp streets after work-hour energy rises.",
      weekdays: [4, 5, 6],
    },
    {
      slug: "sd-la-jolla-coast",
      title: "La Jolla coast half-day",
      time: "09:30",
      timeLabel: "9:30 a.m.",
      duration: "4 hours",
      meetup: "Hotel pickup / La Jolla Cove",
      priceFrom: "$69",
      interest: "City highlights",
      summary: "Cliffs, seals/sea lions viewing windows, and cove walks.",
    },
    {
      slug: "san-hotel-transfer",
      title: "SAN → downtown / Gaslamp transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~15–25 min",
      meetup: "SAN airport",
      priceFrom: "$28",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown San Diego hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("philadelphia", "Philadelphia", "PA", [
    {
      slug: "philly-independence-hall",
      title: "Independence Hall & Old City walk",
      time: "10:00",
      timeLabel: "10:00 a.m.",
      duration: "3 hours",
      meetup: "Independence Visitor Center",
      priceFrom: "$45",
      interest: "City highlights",
      summary: "Founding-era landmarks in Old City Philadelphia.",
    },
    {
      slug: "philly-food-market",
      title: "Reading Terminal & food classics",
      time: "12:00",
      timeLabel: "12:00 p.m.",
      duration: "3 hours",
      meetup: "Reading Terminal Market",
      priceFrom: "$69",
      interest: "Food & markets",
      summary: "Market tastings and Philly food icons.",
    },
    {
      slug: "phl-hotel-transfer",
      title: "PHL → Center City hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~25–40 min",
      meetup: "PHL airport",
      priceFrom: "$32",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into Center City hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("honolulu", "Honolulu", "HI", [
    {
      slug: "honolulu-pearl-harbor",
      title: "Pearl Harbor historic sites day",
      time: "07:00",
      timeLabel: "7:00 a.m.",
      duration: "6–7 hours",
      meetup: "Waikiki hotel pickup",
      priceFrom: "$99",
      interest: "Museums & culture",
      summary: "Pearl Harbor visitor sites with Waikiki hotel pickup.",
      spacesDefault: 14,
    },
    {
      slug: "honolulu-diamond-head",
      title: "Diamond Head sunrise hike",
      time: "06:00",
      timeLabel: "6:00 a.m.",
      duration: "3.5 hours",
      meetup: "Diamond Head crater",
      priceFrom: "$49",
      interest: "City highlights",
      summary: "Crater trail to Pacific viewpoints (timed entry style).",
      weekdays: daily,
    },
    {
      slug: "honolulu-waikiki-evening",
      title: "Waikiki beach evening stroll",
      time: "18:00",
      timeLabel: "6:00 p.m.",
      duration: "2 hours",
      meetup: "Waikiki Beach",
      priceFrom: "$29",
      interest: "Nightlife",
      summary: "Sunset beach corridor walk and photo stops.",
    },
    {
      slug: "hnl-hotel-transfer",
      title: "HNL → Waikiki hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~30–45 min",
      meetup: "HNL airport",
      priceFrom: "$30",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into Waikiki hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("nashville", "Nashville", "TN", [
    {
      slug: "nashville-honky-tonk-evening",
      title: "Honky-tonk Broadway evening",
      time: "19:30",
      timeLabel: "7:30 p.m.",
      duration: "3 hours",
      meetup: "Broadway",
      priceFrom: "$49",
      interest: "Nightlife",
      summary: "Live music corridor orientation on Broadway.",
      weekdays: [3, 4, 5, 6],
    },
    {
      slug: "nashville-country-music-hall",
      title: "Country Music Hall of Fame area",
      time: "11:00",
      timeLabel: "11:00 a.m.",
      duration: "3 hours",
      meetup: "Music Row / Hall of Fame area",
      priceFrom: "$59",
      interest: "Museums & culture",
      summary: "Music history corridor for first-time Nashville visitors.",
    },
    {
      slug: "bna-hotel-transfer",
      title: "BNA → downtown hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~20–35 min",
      meetup: "BNA airport",
      priceFrom: "$28",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown Nashville hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("denver", "Denver", "CO", [
    {
      slug: "denver-red-rocks-half-day",
      title: "Red Rocks amphitheatre half-day",
      time: "09:00",
      timeLabel: "9:00 a.m.",
      duration: "4 hours",
      meetup: "Hotel pickup",
      priceFrom: "$69",
      interest: "City highlights",
      summary: "Iconic Red Rocks visit with Denver hotel pickup.",
    },
    {
      slug: "denver-lohi-food",
      title: "LoHi & downtown food walk",
      time: "12:30",
      timeLabel: "12:30 p.m.",
      duration: "3 hours",
      meetup: "Union Station area",
      priceFrom: "$69",
      interest: "Food & markets",
      summary: "Denver tasting walk across trendy food corridors.",
    },
    {
      slug: "den-hotel-transfer",
      title: "DEN → downtown hotel transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~40–55 min",
      meetup: "DEN airport",
      priceFrom: "$36",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into downtown Denver hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
  ...cityBlock("phoenix", "Phoenix", "AZ", [
    {
      slug: "phoenix-desert-botanical",
      title: "Desert Botanical Garden half-day",
      time: "09:00",
      timeLabel: "9:00 a.m.",
      duration: "3.5 hours",
      meetup: "Hotel pickup / Garden entrance",
      priceFrom: "$65",
      interest: "City highlights",
      summary: "Sonoran Desert plant life and photo trails.",
    },
    {
      slug: "phoenix-scottsdale-art",
      title: "Scottsdale Old Town art walk",
      time: "16:00",
      timeLabel: "4:00 p.m.",
      duration: "2.5 hours",
      meetup: "Old Town Scottsdale",
      priceFrom: "$45",
      interest: "Museums & culture",
      summary: "Galleries and desert-modern streetscapes.",
      weekdays: [3, 4, 5, 6],
    },
    {
      slug: "phx-hotel-transfer",
      title: "PHX → Scottsdale / Downtown transfer",
      time: "",
      timeLabel: "Rolling",
      duration: "~25–45 min",
      meetup: "PHX airport",
      priceFrom: "$32",
      interest: "Airport / hotel transfer",
      summary: "Shared transfer into Phoenix / Scottsdale hotels.",
      schedule: "rolling",
      weekdays: [],
    },
  ]),
];

/** Full USA starter catalog (NYC existing slugs preserved). */
export const catalogTours: CatalogTour[] = [...newYorkTours, ...usaCityTours];

export function listTourMetros(): TourMetro[] {
  return tourMetros;
}

export function getCatalogTour(slug: string) {
  return catalogTours.find((tour) => tour.slug === slug);
}

export function getToursByCity(citySlug: string) {
  if (citySlug === "all") return catalogTours;
  return catalogTours.filter((tour) => tour.citySlug === citySlug);
}

export function catalogStats() {
  const byCity = tourMetros.map((metro) => ({
    ...metro,
    count: catalogTours.filter((t) => t.citySlug === metro.slug).length,
  }));
  return {
    total: catalogTours.length,
    cities: byCity.length,
    byCity,
  };
}
